apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rafahello
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rafahello
    spec:
      containers:
      - name: rafahello
        image: gcr.io/dellemc-219200/rafahello:v2
        ports:
        - name: app-port
          containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: rafahello-web
spec:
  ports:
  - port: 80
    targetPort: app-port
    protocol: TCP
  selector:
    app: rafahello
  type: LoadBalancer

